remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
title: "Ben Eyal"
title_separator: "-"
name: "Ben Eyal"

author:
  name: "Ben Eyal"
  avatar: "/assets/images/profile.png"
  bio: "Working on my PhD in Natural Language Processing @ BGU"